"""new field in user model1

Revision ID: bd2bbc943206
Revises: 7c6ea5ea7323
Create Date: 2022-01-18 17:44:34.256684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd2bbc943206'
down_revision = '7c6ea5ea7323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'about_me')
    op.drop_column('post', 'last_seen')
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    op.add_column('post', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    op.add_column('post', sa.Column('about_me', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
